[2023-11-12T12:44:56.083+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: one_task_dag.one_task manual__2023-11-12T12:44:53.565063+00:00 [queued]>
[2023-11-12T12:44:56.088+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: one_task_dag.one_task manual__2023-11-12T12:44:53.565063+00:00 [queued]>
[2023-11-12T12:44:56.088+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-11-12T12:44:56.089+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-11-12T12:44:56.089+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-11-12T12:44:56.152+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): one_task> on 2023-11-12 12:44:53.565063+00:00
[2023-11-12T12:44:56.159+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'one_task_dag', 'one_task', 'manual__2023-11-12T12:44:53.565063+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/one_task_dag.py', '--cfg-path', '/tmp/tmpjtslhm9o']
[2023-11-12T12:44:56.155+0000] {standard_task_runner.py:55} INFO - Started process 15601 to run task
[2023-11-12T12:44:56.160+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask one_task
[2023-11-12T12:44:56.498+0000] {task_command.py:388} INFO - Running <TaskInstance: one_task_dag.one_task manual__2023-11-12T12:44:53.565063+00:00 [running]> on host codespaces-1a8ad4
[2023-11-12T12:44:56.610+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=one_task_dag
AIRFLOW_CTX_TASK_ID=one_task
AIRFLOW_CTX_EXECUTION_DATE=2023-11-12T12:44:53.565063+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-12T12:44:53.565063+00:00
[2023-11-12T12:44:56.611+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-11-12T12:44:56.612+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo "hello, linkedin learning!" > /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp/one_task.txt/']
[2023-11-12T12:44:56.630+0000] {subprocess.py:86} INFO - Output:
[2023-11-12T12:44:56.638+0000] {subprocess.py:93} INFO - /usr/bin/bash: /workspaces/hands-on-introduction-data-engineering-4395021/lab/temp/one_task.txt/: Is a directory
[2023-11-12T12:44:56.639+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-12T12:44:56.656+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/python/3.10.8/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-12T12:44:56.664+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=one_task_dag, task_id=one_task, execution_date=20231112T124453, start_date=20231112T124456, end_date=20231112T124456
[2023-11-12T12:44:56.710+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 8 for task one_task (Bash command failed. The command returned a non-zero exit code 1.; 15601)
[2023-11-12T12:44:56.736+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-11-12T12:44:56.748+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
